// Modelos iniciais para revisão da clínica. Cada texto pode ser trocado em Ajustes > Procedimentos.
window.CATALOGO_PADRAO = {
  versao: 3,
  geral: [
    'Fui atendido(a) em consulta, tive meu caso avaliado e recebi explicações claras sobre o(s) procedimento(s) marcado(s) neste termo, suas alternativas, os resultados esperados e os riscos.',
    'Tive oportunidade de fazer perguntas e todas foram respondidas. Entendi que a medicina não é uma ciência exata e que o resultado depende também da resposta do meu organismo e dos cuidados que eu seguir, não havendo garantia de resultado específico.',
    'Informei com verdade minhas doenças, alergias, medicamentos em uso, gestação ou amamentação, procedimentos estéticos anteriores e uso de substâncias. Sei que omitir essas informações aumenta o risco de complicações.',
    'Comprometo-me a seguir as orientações antes e depois do procedimento e a comparecer aos retornos combinados. Em caso de qualquer alteração, entrarei em contato com a clínica.',
    'Autorizo o registro fotográfico do meu caso para fins de prontuário e acompanhamento. O uso de imagens para divulgação depende de termo de imagem próprio.',
    'Posso revogar este consentimento a qualquer momento antes do início do procedimento.',
    'Declaro que concordo em assinar este termo por meio eletrônico, com assinatura feita de próprio punho na tela deste dispositivo, e reconheço essa assinatura como válida e equivalente à assinatura em papel, nos termos do art. 10, § 2º, da MP 2.200-2/2001. Recebo cópia deste documento.'
  ],
  procedimentos: [
    { id: 'co2', cat: 'Tecnologias', nome: 'Laser de CO₂ fracionado (protocolo NEON)',
      oque: 'Laser ablativo que cria microcolunas de lesão controlada na pele para estimular renovação e colágeno. Pode ser associado a ativos aplicados logo após o laser.',
      esperar: 'Vermelhidão, inchaço e sensação de calor nos primeiros dias, seguidos de descamação ou crostas finas por cerca de 5 a 10 dias. O resultado se constrói ao longo de semanas a meses.',
      riscos: 'Dor ou ardor; vermelhidão prolongada; manchas escuras (hiperpigmentação) ou claras (hipopigmentação); acne ou milium; infecção bacteriana, viral (reativação de herpes) ou fúngica; cicatriz; queimadura; resultado abaixo do esperado.',
      cuidados: 'Proteção solar rigorosa, não remover crostas, usar os produtos indicados, evitar sol, piscina, sauna e exercício intenso no período orientado.' },
    { id: 'fotona', cat: 'Tecnologias', nome: 'Laser Fotona',
      oque: 'Plataforma de laser (Er:YAG e Nd:YAG) usada para textura, poros, firmeza, manchas e rejuvenescimento, em modos ablativos ou não ablativos conforme a indicação.',
      esperar: 'Calor, vermelhidão e leve inchaço por horas a poucos dias, conforme a intensidade. Pode haver descamação fina.',
      riscos: 'Dor; vermelhidão ou inchaço prolongados; manchas escuras ou claras; queimadura; bolhas; reativação de herpes; cicatriz; resultado abaixo do esperado.',
      cuidados: 'Proteção solar, evitar sol e calor intenso nos dias seguintes, hidratar a pele e seguir os produtos indicados.' },
    { id: 'us', cat: 'Tecnologias', nome: 'Ultrassom micro e macrofocado',
      oque: 'Energia de ultrassom focada em camadas profundas da pele e do tecido de sustentação, para estímulo de colágeno e efeito de firmeza.',
      esperar: 'Desconforto durante a aplicação, vermelhidão e leve inchaço passageiros. O resultado aparece de forma progressiva em 2 a 3 meses.',
      riscos: 'Dor; inchaço; sensibilidade ou dormência local temporária; marcas lineares ou hematomas; queimadura; alteração temporária de nervo com assimetria de movimento (rara); perda de gordura em área indesejada (rara); resultado abaixo do esperado.',
      cuidados: 'Evitar massagem vigorosa na área nos primeiros dias e comunicar qualquer dormência ou alteração de movimento.' },
    { id: 'exion', cat: 'Tecnologias', nome: 'Exion · radiofrequência microagulhada',
      oque: 'Microagulhas que levam energia de radiofrequência para dentro da pele, para textura, poros, cicatrizes e firmeza. Pode ser feita com anestésico.',
      esperar: 'Vermelhidão, inchaço e pequenos pontos na pele por alguns dias.',
      riscos: 'Dor; inchaço; pontos ou marcas temporárias; manchas escuras; acne; infecção; queimadura; cicatriz; reação ao anestésico tópico; resultado abaixo do esperado.',
      cuidados: 'Não usar maquiagem nas primeiras 24 horas, proteção solar e cuidados de higiene orientados.' },
    { id: 'volnewmer', cat: 'Tecnologias', nome: 'Volnewmer · radiofrequência monopolar',
      oque: 'Radiofrequência monopolar que aquece camadas profundas da pele para estimular colágeno e firmeza, com resfriamento da superfície.',
      esperar: 'Sensação de calor durante a aplicação, vermelhidão e leve inchaço passageiros. Resultado progressivo em semanas a meses.',
      riscos: 'Dor; vermelhidão ou inchaço prolongados; bolhas; queimadura; alteração de sensibilidade local; perda de gordura em área indesejada (rara); resultado abaixo do esperado.',
      cuidados: 'Hidratar a pele, proteção solar e comunicar dor persistente ou bolhas.' },
    { id: 'toxina', cat: 'Injetáveis', nome: 'Toxina botulínica',
      oque: 'Aplicação de toxina botulínica em músculos selecionados para suavizar rugas de expressão, ou em outras indicações como suor excessivo.',
      esperar: 'Efeito a partir de 3 a 7 dias, completo em cerca de 15 dias, com duração média de 4 a 6 meses.',
      riscos: 'Dor e pequenos hematomas no ponto da aplicação; dor de cabeça; assimetria; queda da pálpebra ou da sobrancelha (temporária); alteração do sorriso; efeito abaixo ou acima do esperado; reação alérgica (rara).',
      cuidados: 'Não massagear a área e não deitar nas primeiras 4 horas, evitar exercício intenso no dia. Retorno em cerca de 15 dias quando indicado.' },
    { id: 'ah', cat: 'Injetáveis', nome: 'Preenchimento com ácido hialurônico (facial)',
      oque: 'Aplicação de ácido hialurônico para repor volume, sustentar estruturas, contornar e refinar áreas do rosto, com agulha ou cânula.',
      esperar: 'Inchaço, sensibilidade e pequenos hematomas por alguns dias. O resultado se acomoda em cerca de 15 a 30 dias.',
      riscos: 'Dor; hematomas; inchaço; assimetria; nódulos ou irregularidades; migração do produto; infecção; reação inflamatória tardia; oclusão vascular com risco de necrose de pele ou, raramente, alteração visual, situações que exigem atendimento imediato. O ácido hialurônico pode ser dissolvido com hialuronidase se necessário.',
      cuidados: 'Evitar massagear a área, calor intenso e exercício no dia. Procurar a clínica imediatamente em caso de dor forte, palidez ou arroxeamento da pele ou alteração da visão.' },
    { id: 'bio', cat: 'Injetáveis', nome: 'Bioestimulador de colágeno',
      oque: 'Aplicação de substância que estimula a produção de colágeno (como ácido poli-L-láctico ou hidroxiapatita de cálcio) para firmeza e qualidade da pele, no rosto ou no corpo.',
      esperar: 'Inchaço inicial que regride em dias. O resultado é gradual, ao longo de 2 a 3 meses, e pode exigir mais de uma sessão.',
      riscos: 'Dor; hematomas; inchaço; nódulos ou pápulas; irregularidades; infecção; reação inflamatória; oclusão vascular (rara); resultado abaixo do esperado.',
      cuidados: 'Fazer a massagem orientada quando indicada, pelo período combinado, e evitar calor intenso nos primeiros dias.' },
    { id: 'skinbooster', cat: 'Injetáveis', nome: 'Skinbooster',
      oque: 'Microinjeções de ácido hialurônico e ativos na pele para hidratação profunda, viço e textura.',
      esperar: 'Pequenas pápulas e vermelhidão que desaparecem em horas a poucos dias; hematomas pontuais.',
      riscos: 'Dor; hematomas; pápulas persistentes; infecção; reação inflamatória; resultado abaixo do esperado.',
      cuidados: 'Não usar maquiagem nas primeiras 12 horas, evitar calor intenso e exercício no dia.' },
    { id: 'corporal', cat: 'Injetáveis', nome: 'Preenchimento corporal com ácido hialurônico (Body HD)',
      oque: 'Aplicação de ácido hialurônico em áreas do corpo (como glúteo, deltoide, abdômen ou panturrilha) para volume, contorno e definição, podendo ser associado a bioestimulador.',
      esperar: 'Inchaço, sensibilidade e hematomas por alguns dias. O resultado se acomoda em semanas.',
      riscos: 'Dor; hematomas; inchaço; assimetria; nódulos ou irregularidades; migração do produto; infecção; seroma; reação inflamatória tardia; oclusão vascular ou embolia (rara), situações que exigem atendimento imediato.',
      cuidados: 'Evitar exercício intenso, compressão e calor na área pelo período orientado; seguir as orientações de posição para dormir quando indicadas.' },
    { id: 'enzimas', cat: 'Injetáveis', nome: 'Aplicação de enzimas',
      oque: 'Injeção de enzimas e ativos em áreas de gordura localizada ou fibrose, como coadjuvante de contorno.',
      esperar: 'Inchaço, vermelhidão, calor e sensibilidade por alguns dias. Pode exigir várias sessões.',
      riscos: 'Dor; inchaço; hematomas; nódulos; irregularidades; infecção; reação alérgica; resultado abaixo do esperado.',
      cuidados: 'Seguir as orientações de drenagem, hidratação e atividade física.' },
    { id: 'hialuronidase', cat: 'Injetáveis', nome: 'Hialuronidase (dissolução de ácido hialurônico)',
      oque: 'Aplicação de enzima que dissolve o ácido hialurônico, usada para corrigir excesso, irregularidade ou complicação.',
      esperar: 'Redução do volume em horas a dias. Pode ser necessária mais de uma aplicação.',
      riscos: 'Dor; inchaço; vermelhidão; reação alérgica, inclusive grave (rara); perda de volume maior que a desejada.',
      cuidados: 'Comunicar imediatamente qualquer coceira intensa, inchaço fora da área ou falta de ar.' },
    { id: 'imagem_modelo', cat: 'Autorizações', nome: 'Autorização de uso de imagem · paciente modelo (Body HD)',
      oque: 'Autorizo o Dr. Caio Endlich a me fotografar e filmar antes, durante e depois do(s) procedimento(s) deste termo, incluindo o corpo nas áreas tratadas, e a usar essas imagens e vídeos com as finalidades descritas abaixo. Participo como paciente modelo, de forma voluntária, e declaro que não recebo pagamento pelo uso da minha imagem.',
      esperar: 'As imagens poderão ser: (1) enviadas à Rennova, fornecedora dos produtos, apenas para avaliação técnica do caso e liberação dos produtos, sem autorização para a Rennova publicá-las, o que dependerá de autorização específica minha; (2) publicadas nas redes sociais e materiais do Dr. Caio Endlich e da clínica Le Quartier, em formato de antes e depois, vídeo do procedimento e depoimento; (3) usadas em aulas, cursos e mentorias para médicos. O conteúdo seguirá as normas do Conselho Federal de Medicina, sem promessa de resultado.',
      riscos: 'Imagens publicadas na internet podem ser copiadas, salvas e compartilhadas por terceiros, e a retirada completa delas nem sempre é possível, mesmo após a revogação desta autorização.',
      cuidados: 'Posso revogar esta autorização a qualquer momento, por escrito, para usos futuros; publicações já feitas serão retiradas dos perfis do Dr. Caio Endlich e da clínica em até 30 dias. Minhas imagens são dados de saúde e serão tratadas conforme a Lei Geral de Proteção de Dados (Lei 13.709/2018), apenas para as finalidades acima. Posso pedir para não mostrar meu rosto ou para borrar tatuagens e sinais que me identifiquem.' }
  ],
  profissionais: ['Dra. Karla Lessa', 'Dr. Paulo Lessa', 'Dr. Caio Endlich']
};
